locale: 'pt'

backend:
  name: git-gateway
  branch: master

media_library:
  name: uploadcare
  config:
    publicKey: a73a170cb5cdef662983
    multiple: false
    tabs: 'file camera url facebook gdrive'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

collections:
  - name: 'pages'
    label: 'Pages'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/pages/home.md'
        label: 'Home Page'
        name: 'home-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }

      - file: 'content/pages/whatcamera.md'
        label: 'What Camera'
        name: 'whatcamera'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: WhatCamera,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'whatcamera' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/whatfun.md'
        label: 'What Fun'
        name: 'whatfun'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: WhatFun,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'whatfun' }
          - { label: Title, name: title, widget: string }
                
      - file: 'content/pages/what.md'
        label: 'What'
        name: 'what'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: What,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'what' }
          - { label: Title, name: title, widget: string }

  - name: posthome
    label: Home Posts
    editor:
      preview: false
    folder: content/posthome
    slug: '{{slug}}'
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { label: Date / Order, name: date, widget: datetime, dateFormat: "DD.MM.YYYY" }
      # - { name: order, label: Order, widget: number, value_type: "int" }

  - name: postcam
    label: What Camera Posts
    editor:
      preview: false
    folder: content/postcam
    slug: '{{slug}}'
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { label: Date / Order, name: date, widget: datetime, dateFormat: "DD.MM.YYYY" }

  - name: postfun
    label: What Fun Posts
    editor:
      preview: false
    folder: content/postfun
    slug: '{{slug}}'
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { label: Date / Order, name: date, widget: datetime, dateFormat: "DD.MM.YYYY" }

  - name: postwhat
    label: What About
    editor:
      preview: false
    folder: content/postwhat
    slug: '{{slug}}'
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }

  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }
