# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_library:
  name: uploadcare
  config:
    publicKey: a73a170cb5cdef662983
    multiple: false
    tabs: 'file camera url facebook gdrive'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

collections: # A list of collections the CMS should be able to edit
  - name: 'pages'
    label: 'Pages'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: 'content/pages/home.md'
        label: 'Home Page'
        name: 'home-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - { label: Slug, name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/whatcamera.md'
        label: 'What Camera'
        name: 'whatcamera'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: WhatCamera,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'whatcamera' }
          - { label: Title, name: title, widget: string }

      - file: 'content/pages/whatfun.md'
        label: 'What Fun'
        name: 'whatfun'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: WhatFun,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'whatfun' }
          - { label: Title, name: title, widget: string }
                
      - file: 'content/pages/what.md'
        label: 'What'
        name: 'what'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: What,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'what' }
          - { label: Title, name: title, widget: string }

  - name: postHome
    label: Home Posts
    editor:
      preview: true
    folder: content/posthome
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: PostHome }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }

  - name: postCam
    label: What Camera Posts
    editor:
      preview: true
    folder: content/postcam
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: PostCam }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }

  - name: postFun
    label: What Fun Posts
    editor:
      preview: true
    folder: content/postfun
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: PostFun }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }

  - name: postWhat
    label: What About
    editor:
      preview: true
    folder: content/postwhat
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: Template, name: template, widget: hidden, default: PostWhat }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }

  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }
